INSERT into resources (type, name, instagram, web, showDate) VALUES 
("companions", "Orientatión Andujar", "orientacionandujar", "https://linktr.ee/orientacionandujar", null),
("companions", "Baul de Recursos", "baulderecursos", null, null),
("companions", "Living Susana", "living_susana", "https://linktr.ee/living_susana", null),
("companions", "Ayuda para Padres y Maestros", "ayudaparapadresymaestros", "https://ayudaparapadresymaestros.wordpress.com/", null),
("companions", "Peti Pete", "peti.pete", "https://www.teacherspayteachers.com/Store/Petipete", null),
("companions", "El Cerezo Recursos", "elcerezo_recursos", "https://linkr.bio/9rrz0", null),
("companions", "Teacher Helen 28", "teacher_helen28", "https://linktr.ee/elena_helen28", null),
("companions", "Newmero", "newmero", "https://smart.bio/newmero/", null),
("companions", "Jugando con Osbru", "jugandoconosbru", "https://osbrushop.com/", null),
("companions", "Crafter on the Road", "crafter_ontheroad", "https://www.crafterontheroad.com/", null),
("companions", "Susanna Isern", "susannaisern", "https://www.susannaisern.com/", null),
("companions", "Mi Lobo Feroz", "mi_lobo_feroz", "https://www.miloboferoz.com", null),
("companions", "Bonicos Montessori", "bonicos_montessori", "https://linktr.ee/Bonicos", null),
("companions", "Libros de Fieltro Baby Mochy", "libros_de_fieltro_baby_mochy", "https://www.babymochy.com", null),
("companions", "Mi Komikona ES", "mikomikona_es", "https://www.mikomikona.com", null),
("companions", "Las Cosas de Mi Maestra", "lascosasdemimaestra", "https://linktr.ee/lascosasdemimaestra", null),
("companions", "Actividades Princesa", "actividadesprincesas", null, null),
("companions", "Ababol Libros de Fieltro", "ababollibrosdefieltro", null, null),
("companions", "Aprendiendo Juntos Neuropsi", "aprendiendojuntosneuropsi", "https://www.aprendiendojuntosneuropsi.com/post/educar-con-l%C3%ADmites", null),
("companions", "El Diario de mi Aula", "eldiariodemiaula", "https://eldiariodemiaulablog.blogspot.com/", null),
("companions", "Colourful Chilhood Education", "colourful_childhood_education", null, null),
("companions", "La Casita Educativa", "la_casita_educativa", "https://lacasitaeducativa.shop/", null),
("companions", "OrientaMedia Gabinete", "orientamediagabinete", "https://linktr.ee/orientamedia", null),
("companions", "Iria Be", "mansdeouro", "https://mansdeouro.com/", null),
("companions", "Psic. M. Paz Ruiz", "psico_mporienta", "https://eduki.com/es/autor/1351256/psico-mporienta", null),
("companions", "KumuBox", "kumubox", "https://kumubox.com/link-en-la-bio/", null),
("companions", "Maestra Especial", "maestraespecial", "https://linktr.ee/maestraespecial", null),
("companions", "Educamaría", "educamariaa", "https://educamaria.com/", null),
("companions", "Seño Lidia", "srta_wabisabi", "https://linktr.ee/srtawabisabi", null),
("companions", "Maestra Malena", "maestramalena", null, null),
("companions", "Tiza y Fantasia", "tizayfantasia", "https://linktr.ee/tizayfantasia", null),
("companions", "Psico Cortex", "psicocortex", "https://linktr.ee/psicocortex", null),
("companions", "Tania - La mademoiselle du FLE", "lamademoiselledufle", "https://beacons.ai/lamademoiselledufle", null),
("theories", "Calculo ABN", null, "https://calculoabn.com/", "2022/06/10 01:01:00"),
("theories", "Doble Equipo Valencia", null, "https://www.dobleequipovalencia.com/", "2022/06/10 01:01:00"),
("theories", "Neuro Class", null, "https://neuro-class.com/", "2022/06/10 01:01:00"),
("theories", "Guías Junta de Andalucía", null, "https://www.juntadeandalucia.es/organismos/igualdadpoliticassocialesyconciliacion/areas/discapacidad/publicaciones/paginas/guias-discapacidad.html", "2022/06/10 01:01:00"),
("theories", "Aprendiendo Matemáticas", null, "https://aprendiendomatematicas.com/blog/", "2022/06/10 01:01:00"),
("theories", "El sonido de la hierba al crecer", null, "https://elsonidodelahierbaelcrecer.blogspot.com/", "2022/06/10 01:01:00"),
("theories", "Educación 3.0", null, "https://www.educaciontrespuntocero.com/recursos/recursos-dislexia-alumnos/", "2022/06/10 01:01:00"),
("theories", "Cuadernos de Pedagogía", null, "https://www.cuadernosdepedagogia.com/content/Inicio.aspx", "2022/06/10 01:01:00"),
("theories", "Educación 3.0", null, "https://www.educaciontrespuntocero.com/recursos/recursos-dislexia-alumnos/", "2022/06/10 01:01:00"),
("theories", "Graó", null, "https://www.grao.com/es/productos/escuela-inclusiva", "2022/06/10 01:01:00"),
("theories", "Creena Navarra", null, "https://creena.educacion.navarra.es/web/", "2022/06/10 01:01:00"),
("theories", "Fundación CADAH", null, "https://www.fundacioncadah.org/web/categoria/tdah-preescolar.html", "2022/06/10 01:01:00")
